from . import res_company
from . import res_config_settings
from . import rent_amenity
from . import rent_property
from . import rent_unit
from . import res_partner
from . import rent_lease
from . import rent_maintenance_request
from . import rent_electricity_reading
from . import account_move
from . import rent_dashboard
